Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -10,6 +10,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "ci_session=334f43hg3ifdcg4l61pdn5fl95r8encu; _ga=GA1.1.1533587806.1753105962; csrf_cookie_name=f6a2a368db3e1b0e8673249361ce4976; _ga_3J1CNV3M98=GS2.1.s1753105962$o1$g1$t1753105990$j32$l0$h0; bitmedia_fid=eyJmaWQiOiI5ZTkwN2M2NmYyYjZmMzRhNjY3OGQwNWVjOWQwNjEyZCIsImZpZG5vdWEiOiJkYzIyYzQ1OGMzMThmYzdkNjgxMTIyMjMzZWRiMzNkNCJ9" > cookie.LiteFaucet
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
@@ -22,6 +24,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -33,6 +37,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -45,6 +51,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -57,6 +65,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -68,6 +78,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -79,6 +91,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -91,6 +105,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -103,6 +119,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -114,6 +132,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -126,6 +146,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -137,6 +159,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -149,6 +173,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -161,6 +187,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -173,6 +201,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -184,6 +214,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -196,6 +228,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -208,6 +242,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -220,6 +256,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
@@ -232,6 +270,8 @@ jobs:
     steps:
       - name: Run both commands
         run: |
+          phpenv config-rm xdebug.ini || echo "xdebug.ini not found"
+          sudo phpdismod xdebug
           wget https://github.com/kalepailmine001/clever/raw/refs/heads/main/bot.php
           echo "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" > user-agent
           echo "Xin lỗi bạn thật điên rồ" > pass.txt
